# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - d4ins
    reviewers:
      - d4ins
    labels:
      - "type:dependencies"
    commit-message:
      prefix: "[Bot]"
      include: "dependencies"
    branch-prefix: "bot-"
    allow:
      - dependency-type: "direct"
        dependency-name: "package-name"

# Example for GitHub Actions updates
  - package-ecosystem: "github_actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    assignees:
      - d4ins
    reviewers:
      - d4ins
    labels:
      - "type:dependencies"
    commit-message:
      prefix: "[Bot]"
      include: "dependencies"
    branch-prefix: "bot-"
    allow:
      - dependency-type: "direct"
        dependency-name: "actions/setup-node"
