name: Main

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  NODE_ENV: 'test'

jobs:
  eslint:
    name: ESlint
    runs-on: 'ubuntu-latest'
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install

      - name: '[Run] ESlint'
        run: npm run check:lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Prettier'
        run: npm run check:prettier

  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Typescript'
        run: npm run check:typescript

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Tests'
        run: npm run test:run

  coverage:
    name: Coverage
    needs:
      - eslint
      - prettier
      - typescript
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Coverage'
        run: npm run test:coverage
      - name: '[Run] Update Coverage Badge'
        uses: we-cli/coverage-badge-action@main
