name: Main

on:
  workflow_dispatch:
  push:
    branches: ['main']

env:
  NODE_ENV: 'test'

jobs:
  eslint:
    name: 'ESlint'
    uses: ./.github/workflows/re-eslint.yml

  prettier:
    name: 'Prettier'
    uses: ./.github/workflows/re-prettier.yml

  typescript:
    name: 'Typescript'
    uses: ./.github/workflows/re-typescript.yml

  tests:
    name: 'Tests'
    uses: ./.github/workflows/re-tests.yml

  copy-actions:
    name: 'Copy actions'
    needs:
      - eslint
      - prettier
      - typescript
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '[GIT] Add user.email'
        run: git config --global user.email "${{ vars.BOT_EMAIL }}"

      - name: '[GIT] Add user.name'
        run: git config --global user.name "${{ vars.BOT_USERNAME }}"

      - name: '[Prepare] Copy actions directory'
        run: cp -r ./.github/workflows ./.github/tmp

      - name: '[Debug] ls'
        run: ls -la './.github

      - name: '[GIT] Switch to gh-pages'
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: '[Debug] ls'
        run: ls -la './.github

      - name: '[GIT] Create branch'
        run: git checkout -b bot-actions-update

      - name: '[Debug] ls'
        run: ls -la './.github

      - name: '[Prepare] Copy actions directory'
        run: cp -rf ./.github/tmp/ ./.github/workflows/

      - name: '[GIT] Add workflows'
        run: git add github/workflows

      - name: '[GIT] Commit'
        run: git commit -a -m "[Bot] Update actions"

      - name: '[GIT] Push'
        env:
          TOKEN: ${{ secrets.BOT_KEY }}
        run: git push https://github.com/${{ github.repository }}.git HEAD:bot-badge-update

      - name: '[GIT] Create PR'
        env:
          GH_TOKEN: ${{ secrets.BOT_KEY }}
        run: |
          gh pr create \
            --base gh-pages \
            --head bot-actions-update \
            --title "[Bot] Actions update" \
            --body "This PR is automatically created by BOT and will be merge automatically as well."
      

  coverage:
    name: Coverage
    needs:
      - copy-actions
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json

      - name: '[Setup] Install dependencies'
        run: npm install

      - name: '[Run] Coverage'
        run: npm run test:summary

      - name: '[Prepare] Get percentage'
        id: get-values
        shell: bash
        run: |
          COV=$(node -p 't=require(`./coverage/coverage-summary.json`).total,Math.min(...`lines|statements|functions|branches`.split(`|`).map(k=>t[k].pct))')
          echo "coverage=$COV" >> $GITHUB_OUTPUT

      - name: '[GIT] Switch to gh-pages'
        uses: actions/checkout@v4
        with:
          ref: gh-pages

      - name: '[GIT] Create branch'
        run: git checkout -b bot-badge-update

      - name: '[Setup] Install badgen'
        run: npm i -g badgen-cli

      - name: '[Setup] Create badge directory'
        run: mkdir -p assets/badges

      - name: '[Run] Create Badges'
        shell: bash
        run: |
          export COV=${{ steps.get-values.outputs.coverage }}
          COLOR=$(node -p '+process.env.COV >= 95 ? `green` : `orange`')
          badgen -j coverage -s $COV% -c $COLOR > assets/badges/coverage.svg

      - name: '[GIT] Add user.email'
        run: git config --global user.email "${{ vars.BOT_EMAIL }}"

      - name: '[GIT] Add user.name'
        run: git config --global user.name "${{ vars.BOT_USERNAME }}"

      - name: '[GIT] Add badges'
        run: git add assets/badges

      - name: '[GIT] Commit'
        run:  git commit -a -m "[Bot] Update coverage badge"

      - name: '[GIT] Push'
        env:
          TOKEN: ${{ secrets.BOT_KEY }}
        run: git push https://github.com/${{ github.repository }}.git HEAD:bot-badge-update

      - name: '[GIT] Create PR'
        env:
          GH_TOKEN: ${{ secrets.BOT_KEY }}
        run: |
          gh pr create \
            --base gh-pages \
            --head bot-badge-update \
            --title "[Bot] Badge update" \
            --body "This PR is automatically created by BOT and will be merge automatically as well."
