name: Main

on:
  push:
    branches: ['main']
  workflow_dispatch:

env:
  NODE_ENV: 'test'

jobs:
  eslint:
    name: ESlint
    runs-on: 'ubuntu-latest'
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install

      - name: '[Run] ESlint'
        run: npm run check:lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Prettier'
        run: npm run check:prettier

  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Typescript'
        run: npm run check:typescript

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Tests'
        run: npm run test:run

  coverage:
    name: Coverage
    needs:
      - eslint
      - prettier
      - typescript
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Coverage'
        run: npm run test:summary
      - name: '[Prepare] Get percentage'
        id: get-values
        shell: bash
        run: |
          COV=$(node -p 't=require(`./coverage/coverage-summary.json`).total,Math.min(...`lines|statements|functions|branches`.split(`|`).map(k=>t[k].pct))')
          echo "coverage=$COV" >> $GITHUB_OUTPUT
      - name: '[GIT] Switch branch'
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: '[Setup] Install badgen'
        run: npm i -g badgen-cli
      - name: '[Setup] Create badge directory'
        run: mkdir -p badges
      - name: '[Run] Create Badges'
        shell: bash
        run: |
          export COV=${{ steps.get-values.outputs.coverage }}
          COLOR=$(node -p '+process.env.COV >= 95 ? `green` : `orange`')
          badgen -j coverage -s $COV% -c $COLOR > badges/coverage.svg
      - name: '[GIT] Commit'
        run:  git commit -a -m "[Bot] Update coverage badge"
      - name: '[GIT] Push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_KEY }}
          branch: ${{ github.ref }}
