name: 'Pull Request: Bot'

on:
  pull_request:
    branches:
      - main
      - gh-pages

jobs:
  merge:
    name: "Merge"
    runs-on: ubuntu-latest

    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: '[Check] PR name'
        run: |
          if [[ ${{ github.event.action }} == 'opened' && "${{ github.event.pull_request.title }}" == '[Bot] Badge update' ]]; then
            echo "PR with specific name detected. Proceeding to check if required checks have passed."
          else
            echo "PR does not have the specific name. Skipping auto-merge."
            exit 0 
          fi

      - name: '[GIT] Merge'
        run: gh pr merge ${{ github.event.number }} --auto --squash --admin

      - name: '[GIT] Clean branch'
        env:
          GH_TOKEN: ${{ secrets.BOT_KEY }}
        run: git push origin -d bot-badge-update || echo "Branch bot-badge-update does not exist, skipping deletion"
