name: 'Re: Typescript'

on:
  workflow_call:

jobs:
  typescript:
    name: 'Typescript'
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4

      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json

      - name: '[Setup] Install dependencies'
        run: npm install

      - name: '[Run] Typescript'
        run: npm run check:typescript
