name: 'Release'

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'What will be the release version?'
        required: true
        default: 0.0.1
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  eslint:
    name: 'ESlint'
    uses: ./.github/workflows/re-eslint.yml

  prettier:
    name: 'Prettier'
    uses: ./.github/workflows/re-prettier.yml

  typescript:
    name: 'Typescript'
    uses: ./.github/workflows/re-typescript.yml

  tests:
    name: 'Tests'
    uses: ./.github/workflows/re-tests.yml

  release:
    name: 'Release'
    needs:
      - eslint
      - prettier
      - typescript
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org'

      - name: '[Prepare] Change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ inputs.version }}

      - name: '[Setup] Install dependencies'
        run: npm ci --ignore-scripts

      - name: '[Build] Run'
        run: npm run build

      - name: '[Publish] NPM'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}

  actualise:
    name: "Actualise"
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: '[GIT] Create branch'
        run: git checkout -b bot-actualisation

      - name: '[Prepare] Change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ inputs.version }}

      - name: '[GIT] Add user.email'
        run: git config --global user.email "${{ vars.BOT_EMAIL }}"

      - name: '[GIT] Add user.name'
        run: git config --global user.name "${{ vars.BOT_USERNAME }}"

      - name: '[GIT] Add package.json'
        run: git add package.json

      - name: '[GIT] Commit'
        run: git commit -a -m "[Bot] Actualisation of branch"

      - name: '[GIT] Push'
        env:
          TOKEN: ${{ secrets.BOT_KEY }}
        run: git push https://github.com/${{ github.repository }}.git HEAD:bot-actualisation

      - name: '[GIT] Create PR'
        env:
          GH_TOKEN: ${{ secrets.BOT_KEY }}
        run: |
          gh pr create \
            --base main \
            --head bot-actualisation \
            --title "[Bot] Branch actualisation" \
            --body "This PR is automatically created by BOT and will be merge automatically as well."
