name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'What will be the release version?'
        required: true
        default: 0.0.1
        type: string

permissions:
  id-token: write
  contents: write

jobs:
  eslint:
    name: ESlint
    runs-on: 'ubuntu-latest'
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] ESlint'
        run: npm run check:lint

  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Prettier'
        run: npm run check:prettier

  typescript:
    name: Typescript
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Typescript'
        run: npm run check:typescript

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
      - name: '[Setup] Install dependencies'
        run: npm install
      - name: '[Run] Tests'
        run: npm run test:run

  release:
    name: Release
    needs:
      - eslint
      - prettier
      - typescript
      - tests
    runs-on: ubuntu-latest
    steps:
      - name: '[Setup] Checkout'
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: '[Setup] Node.js'
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc
          check-latest: false
          cache: npm
          cache-dependency-path: package-lock.json
          registry-url: 'https://registry.npmjs.org'
      - name: '[Prepare] Change version'
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ inputs.version }}
      - name: '[Setup] Install dependencies'
        run: npm ci --ignore-scripts
      - name: '[Build] Run'
        run: npm run build
      - name: '[Publish] NPM'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: '[GIT] User'
        run: |
          git config --local user.email "${{ env.BOT_EMAIL }}"
          git config --local user.name "${{ env.BOT_USERNAME }}"
      - name: '[GIT] Commit'
        run:  git commit -a -m "[Bot] Update package.json version"
      - name: '[GIT] Push'
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.BOT_KEY }}
          branch: ${{ github.ref }}
      - name: '[Publish] Tag'
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: "v${{ inputs.version }}"
          tag_exists_error: true
          message: "Release ${{ inputs.version }}"

